[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "OpenbindDiff2IR"
authors = [{name = "Conor F Wild", email = "c.wild@diamond.ac.uk"}]
dynamic = ["version", "description"]
